import React, { useState, useEffect } from 'react';
import { 
  CalendarClock, 
  AlertTriangle, 
  RefreshCw, 
  Zap, 
  CheckCircle2, 
  UserCheck, 
  Cpu,
  ArrowRight,
  ShieldCheck
} from 'lucide-react';

export default function ReactiveTimetable() {
  const [schedule, setSchedule] = useState([]);
  const [loading, setLoading] = useState(true);
  const [solvingDisruption, setSolvingDisruption] = useState(false);
  const [disruptionResult, setDisruptionResult] = useState(null);
  const [selectedTeacher, setSelectedTeacher] = useState('T101'); // Dr. Ramesh Verma

  const days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"];
  const periods = [1, 2, 3, 4, 5, 6];

  // Fetch initial timetable generated by Google OR-Tools
  useEffect(() => {
    fetchTimetable();
  }, []);

  const fetchTimetable = async () => {
    setLoading(true);
    try {
      const res = await fetch('/api/timetable/generate');
      const data = await res.json();
      setSchedule(data.schedule || []);
      setLoading(false);
    } catch (err) {
      console.error(err);
      setLoading(false);
    }
  };

  const handleSimulateDisruption = async () => {
    setSolvingDisruption(true);
    setDisruptionResult(null);

    try {
      // Simulate CP-SAT constraint resolution delay for WOW effect
      await new Promise(r => setTimeout(r, 1200));

      const res = await fetch('/api/timetable/disruption', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ teacher_id: selectedTeacher, day: "Monday" })
      });
      const data = await res.json();
      setSolvingDisruption(false);
      setDisruptionResult(data);
    } catch (err) {
      setSolvingDisruption(false);
      console.error(err);
    }
  };

  const applyReassignments = () => {
    if (!disruptionResult) return;
    
    // Update local schedule state to reflect the sub reassignments
    const updated = schedule.map(slot => {
      const resolution = disruptionResult.resolutions.find(r => r.period === slot.period && slot.day === "Monday" && slot.teacher_id === selectedTeacher);
      if (resolution) {
        return {
          ...slot,
          teacher_name: resolution.recommended_substitute,
          teacher_id: resolution.substitute_id,
          is_reassigned: true
        };
      }
      return slot;
    });

    setSchedule(updated);
    setDisruptionResult(null);
  };

  return (
    <div className="p-8 space-y-8 max-w-7xl mx-auto">
      {/* Header Banner */}
      <div className="glass-panel p-6 rounded-2xl flex flex-col lg:flex-row lg:items-center justify-between gap-6">
        <div>
          <div className="flex items-center gap-2">
            <span className="text-xs font-bold uppercase tracking-wider text-blue-400 bg-blue-500/20 px-2.5 py-0.5 rounded border border-blue-500/30">
              CP-SAT Constraint Solver
            </span>
            <span className="text-xs text-slate-400">Google OR-Tools Engine</span>
          </div>
          <h2 className="text-xl font-extrabold text-white mt-1">
            Reactive Timetable & Live Disruption Engine
          </h2>
          <p className="text-xs text-slate-300 mt-1 max-w-2xl">
            Schedules are generated with 0 double-booking constraints. When a teacher calls in sick, the Air Traffic Control solver reallocates classes instantly.
          </p>
        </div>

        {/* Live Disruption Simulator Trigger */}
        <div className="glass-panel-accent p-4 rounded-xl flex items-center gap-4 shrink-0">
          <div>
            <label className="text-[11px] font-bold text-amber-300 uppercase tracking-wider block">Simulate Sick Leave</label>
            <select
              value={selectedTeacher}
              onChange={(e) => setSelectedTeacher(e.target.value)}
              className="bg-slate-900 border border-slate-700 text-white text-xs rounded-lg p-2 mt-1 focus:ring-2 focus:ring-amber-500 outline-none"
            >
              <option value="T101">Dr. Ramesh Verma (Math/Phys)</option>
              <option value="T102">Ms. Ananya Gupta (Eng/Hist)</option>
              <option value="T103">Mr. Vikram Singh (Chem/Bio)</option>
            </select>
          </div>

          <button
            onClick={handleSimulateDisruption}
            disabled={solvingDisruption}
            className="px-4 py-2.5 bg-amber-500 hover:bg-amber-400 text-slate-950 font-bold text-xs rounded-xl shadow-lg shadow-amber-500/20 flex items-center gap-2 transition cursor-pointer"
          >
            <AlertTriangle className="w-4 h-4" />
            <span>Trigger Sick Event</span>
          </button>
        </div>
      </div>

      {/* Solver In Progress Modal / Overlay */}
      {solvingDisruption && (
        <div className="glass-panel p-8 rounded-2xl border border-blue-500/50 flex flex-col items-center justify-center space-y-4 pulse-glow-blue animate-pulse">
          <div className="relative">
            <Cpu className="w-12 h-12 text-blue-400 animate-spin" />
            <Zap className="w-6 h-6 text-amber-400 absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2" />
          </div>
          <div className="text-center space-y-1">
            <h3 className="text-lg font-bold text-white">Google OR-Tools Solver Running...</h3>
            <p className="text-xs text-blue-300">
              Evaluating 1,440 constraint variables: Checking teacher availability, room capacity, and subject specialization...
            </p>
          </div>
        </div>
      )}

      {/* Disruption Solution Drawer */}
      {disruptionResult && (
        <div className="glass-panel p-6 rounded-2xl border-2 border-amber-500/50 bg-slate-900/90 space-y-4 shadow-2xl">
          <div className="flex items-center justify-between border-b border-slate-800 pb-3">
            <div className="flex items-center gap-2">
              <AlertTriangle className="w-5 h-5 text-amber-400" />
              <h3 className="text-base font-bold text-white">
                Disruption Solution Calculated ({disruptionResult.total_affected_periods} affected periods)
              </h3>
            </div>
            <span className="text-xs text-amber-400 font-mono">Solve Time: 0.04s</span>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {disruptionResult.resolutions.map((res, idx) => (
              <div key={idx} className="bg-slate-950/80 p-4 rounded-xl border border-slate-800 space-y-2">
                <div className="flex items-center justify-between text-xs">
                  <span className="font-bold text-blue-400">Period {res.period} • {res.cohort_name}</span>
                  <span className={`px-2 py-0.5 rounded text-[10px] font-bold ${
                    res.is_specialist ? 'bg-emerald-500/20 text-emerald-300' : 'bg-slate-800 text-slate-400'
                  }`}>
                    {res.is_specialist ? 'Subject Specialist' : 'General Supervisor'}
                  </span>
                </div>
                <p className="text-xs text-slate-300">
                  Subject: <strong className="text-white">{res.affected_subject}</strong>
                </p>
                <p className="text-xs text-emerald-400 font-medium flex items-center gap-1.5">
                  <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                  Recommended: {res.recommended_substitute}
                </p>
              </div>
            ))}
          </div>

          <div className="flex justify-end gap-3 pt-2">
            <button
              onClick={() => setDisruptionResult(null)}
              className="px-4 py-2 bg-slate-800 text-slate-300 text-xs font-semibold rounded-xl hover:bg-slate-700 cursor-pointer"
            >
              Dismiss
            </button>
            <button
              onClick={applyReassignments}
              className="px-5 py-2 bg-emerald-500 hover:bg-emerald-400 text-slate-950 font-bold text-xs rounded-xl shadow-lg shadow-emerald-500/20 flex items-center gap-2 cursor-pointer"
            >
              <CheckCircle2 className="w-4 h-4" />
              <span>Execute Reassignments Live</span>
            </button>
          </div>
        </div>
      )}

      {/* Master Timetable Matrix */}
      <div className="glass-panel p-6 rounded-2xl overflow-x-auto">
        <div className="flex items-center justify-between mb-4">
          <h3 className="text-sm font-bold text-slate-300 uppercase tracking-wider">
            Grade 10-A Weekly Schedule Matrix
          </h3>
          <span className="text-xs text-slate-400 flex items-center gap-1 font-mono">
            <ShieldCheck className="w-4 h-4 text-emerald-400" />
            0 Conflicts Detected
          </span>
        </div>

        <table className="w-full text-left border-collapse min-w-[700px]">
          <thead>
            <tr className="border-b border-slate-800 text-xs text-slate-400 uppercase">
              <th className="py-3 px-4">Period</th>
              {days.map(day => (
                <th key={day} className="py-3 px-4">{day}</th>
              ))}
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-800/60 text-xs">
            {periods.map(p => (
              <tr key={p} className="hover:bg-slate-800/30 transition">
                <td className="py-4 px-4 font-mono font-bold text-blue-400">P{p}</td>
                {days.map(day => {
                  const slot = schedule.find(s => s.day === day && s.period === p && s.cohort_id === 'C10A');
                  if (!slot) return <td key={day} className="py-4 px-4 text-slate-600">Free</td>;

                  return (
                    <td key={day} className="py-4 px-4">
                      <div className={`p-2.5 rounded-xl border transition ${
                        slot.is_reassigned 
                          ? 'bg-emerald-500/20 border-emerald-500/40 text-emerald-200 pulse-glow-green' 
                          : 'bg-slate-900/60 border-slate-800 text-slate-200'
                      }`}>
                        <p className="font-bold text-white text-xs">{slot.subject_name}</p>
                        <p className="text-[11px] text-slate-400 mt-0.5">{slot.teacher_name}</p>
                        <span className="text-[10px] text-indigo-400 font-mono block mt-1">{slot.room_name}</span>
                      </div>
                    </td>
                  );
                })}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
