import React from 'react';
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: {
    padding: 30,
    backgroundColor: '#ffffff',
    fontFamily: 'Helvetica',
  },
  header: {
    marginBottom: 24,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  title: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#0f162a',
    letterSpacing: -0.5,
  },
  subtitle: {
    fontSize: 10,
    color: '#63748a',
    marginTop: 6,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  grid: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    borderTop: '1px solid #f0f5f8',
    borderLeft: '1px solid #f0f5f8',
    borderRadius: 4,
  },
  row: {
    flexDirection: 'row',
  },
  cellHeader: {
    flex: 1,
    padding: 6,
    backgroundColor: '#f8f9fb',
    borderRight: '1px solid #f0f5f8',
    borderBottom: '1px solid #f0f5f8',
    fontSize: 9,
    fontWeight: 'bold',
    color: '#465469',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    textAlign: 'center',
    justifyContent: 'center',
  },
  cell: {
    flex: 1,
    padding: 6,
    borderRight: '1px solid #f0f5f8',
    borderBottom: '1px solid #f0f5f8',
    minHeight: 48,
    justifyContent: 'center',
    alignItems: 'center',
  },
  subjectText: {
    fontSize: 8,
    fontWeight: 'bold',
    color: '#0f162a',
    marginBottom: 2,
    textAlign: 'center',
  },
  teacherText: {
    fontSize: 7,
    color: '#465469',
    textAlign: 'center',
  },
  substituteText: {
    fontSize: 7,
    color: '#f59e0a',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 30,
    right: 30,
    fontSize: 8,
    color: '#93a2b8',
    textAlign: 'center',
    borderTop: '1px solid #e1e8ef',
    paddingTop: 10,
  }
});

const PristineTimetablePDF = ({ schedule, days, periods, options = {} }) => {
  const getSlot = (day, period) => {
    return schedule.find(s => s.day === day && s.period === period);
  };

  return (
    <Document>
      <Page size="A4" orientation="landscape" style={styles.page}>
        <View style={styles.header}>
          <View>
            <Text style={styles.title}>Victory High School - Master Timetable</Text>
            <Text style={styles.subtitle}>Generated by EduFlow OS • Pristine Print Engine</Text>
          </View>
        </View>

        <View style={styles.grid}>
          <View style={styles.row}>
            <View style={styles.cellHeader}>
              <Text>Time / Day</Text>
            </View>
            {days.map(day => (
              <View key={day} style={styles.cellHeader}>
                <Text>{day}</Text>
              </View>
            ))}
          </View>

          {periods.map(period => (
            <View key={period} style={styles.row}>
              <View style={styles.cellHeader}>
                <Text>Period {period}</Text>
              </View>
              {days.map(day => {
                const slot = getSlot(day, period);
                if (!slot && options.hideEmpty) {
                   return <View key={`${day}-${period}`} style={[styles.cell, { backgroundColor: '#f0f5f8' }]}><Text></Text></View>;
                }
                
                return (
                  <View key={`${day}-${period}`} style={styles.cell}>
                    {slot ? (
                      <>
                        <Text style={styles.subjectText}>{slot.subject}</Text>
                        <Text style={slot.is_reassigned ? styles.substituteText : styles.teacherText}>
                          {slot.is_reassigned ? `Sub: ${slot.teacher_name}` : slot.teacher_name}
                        </Text>
                      </>
                    ) : (
                      <Text style={styles.teacherText}>-</Text>
                    )}
                  </View>
                );
              })}
            </View>
          ))}
        </View>

        <View style={styles.footer}>
          <Text>This document is cryptographically synchronized with the live CP-SAT engine. Do not alter manually.</Text>
        </View>
      </Page>
    </Document>
  );
};

export default PristineTimetablePDF;
